---
development:
  cloud_name: <%= Rails.application.credentials[:development][:cloud_name] %>
  api_key: <%= Rails.application.credentials[:development][:api_key] %>
  api_secret: <%= Rails.application.credentials[:development][:api_secret] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= Rails.application.credentials[:development][:cloud_name] %>
  api_key: <%= Rails.application.credentials[:development][:api_key] %>
  api_secret: <%= Rails.application.credentials[:development][:api_secret] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= Rails.application.credentials[:development][:cloud_name] %>
  api_key: <%= Rails.application.credentials[:development][:api_key] %>
  api_secret: <%= Rails.application.credentials[:development][:api_secret] %>
  enhance_image_tag: true
  static_file_support: false
