---
development:
  cloud_name: mwaqas
  api_key: '565792764927223'
  api_secret: Xh2afZa6hlPMtiGwyFhZIrPvcX0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: mwaqas
  api_key: '565792764927223'
  api_secret: Xh2afZa6hlPMtiGwyFhZIrPvcX0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: mwaqas
  api_key: '565792764927223'
  api_secret: Xh2afZa6hlPMtiGwyFhZIrPvcX0
  enhance_image_tag: true
  static_file_support: false
